name: yx_scope_linter
description: A package that contains static analysis rules for yx_scope DI framework
version: 0.2.0
repository: https://github.com/yandex/city-services-pub/tree/main/yx_scope/packages/yx_scope_linter
issue_tracker: https://github.com/yandex/city-services-pub/issues
topics:
  - di
  - scope
  - dependency-injection
  - dependency-management

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  analyzer: '>=6.4.1 <8.0.0'
  analyzer_plugin: '>=0.11.2 <0.14.0'
  custom_lint_builder: '>=0.6.2 <0.8.0'
  yx_scope: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  custom_lint: '>=0.6.8 <0.8.0'
